### PR TITLE
Make loader return svgo errors on failed optimisation

### PR DESCRIPTION
**Pull request by rdjpalmer**
Currently the loader is swallowing any errors returned by svgo. The change exposes the error which makes it much easier to debug when svgo fails to optimise an svg.

### CODE REVIEW

**Comment by rpominov** [comment]
Hi. Thank you for the PR!

Could you add an example for this similar to one in `test` directory? You can move current example into `test/success` and put another one into `test/svgo-error`.

**Comment by rdjpalmer** [comment]
@rpominov Sure thing. I've added the erroring example, and also renamed `/test` to `/example` as I think it gives a better idea of the intention for the code in there

**Comment by rpominov** [comment]
Great! Could you also edit `.gitignore` like this: 

``` diff
-test/dist
+test/**/dist
```

and remove `example/svgo-error/dist`?

**Comment by rdjpalmer** [comment]
@rpominov All done!

**Comment by rpominov** [comment]
`example/svgo-error/dist` is still in the PR's diff. You need to manually `git remove` it even though it matches pattern in `.gitignore`.

**Comment by rdjpalmer** [comment]
Derp. All fixed :)

**Comment by rpominov** [comment]
I've released `v1.1.1` with this fix. Thank you!

**Comment by rdjpalmer** [comment]
@rpominov Excellent! You're very welcome. Thanks for the quick response time 😀

**Pull request merged**
